baseURL = 'https://padmanabhansaravanan.github.io/'
title = 'Swayaan LMS'

# Hugo allows theme composition (and inheritance). The precedence is from left to right.
#theme = ["docsy"]

# Language settings
contentDir = "content/en"

[module]
  proxy = "direct"
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.73.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false

staticDir = ['static']

[params]
# Google Custom Search Engine ID. Remove or comment out to disable search.
gcs_engine_id = "011737558837375720776:fsdu1nryfng"

# privacy_policy = "https://policies.google.com/privacy"

# Menu title if your navbar has a versions selector to access old versions of your site.
# This menu appears only if you have at least one [params.versions] set.
version_menu = "Versions"

time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 02, 2006 at 3:04 PM PST"

# See code_sample shortcode
githubWebsiteRaw = "raw.githubusercontent.com/PadmanabhanSaravanan/website"

# GitHub repository link for editing a page and opening issues.
github_repo = "https://github.com/PadmanabhanSaravanan/website"


# Enable Algolia DocSearch
algolia_docsearch = false

# Enable Lunr.js offline search
offlineSearch = false

# Official CVE feed bucket URL
cveFeedBucket = "https://storage.googleapis.com/k8s-cve-feed/official-cve-feed.json"

[params.pushAssets]
css = [
  "callouts",
  "styles"
]
js = [
  "script"
]

# User interface configuration
[params.ui]
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = false
# Show expand/collapse icon for sidebar sections.
sidebar_menu_foldable = true
# https://github.com/gohugoio/hugo/issues/8918#issuecomment-903314696
sidebar_cache_limit = 1
# Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top nav bar
navbar_logo = true
# Set to true to disable the About link in the site footer
footer_about_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
yes = 'Glad to hear it! Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'
no = 'Sorry to hear that. Please <a href="https://github.com/USERNAME/REPOSITORY/issues/new">tell us how we can improve</a>.'

[params.links]

[[params.links.user]]
	name = "Twitter"
	url = "https://twitter.com/"
	icon = "fab fa-twitter"
	desc = "Follow us on Twitter to get the latest news!"

[[params.links.user]]
	name = "Calendar"
	url = "https://calendar.google.com/calendar"
	icon = "fas fa-calendar-alt"
	desc = "Google Calendar"

[[params.links.user]]
	name = "Youtube"
	url = "https://youtube.com"
	icon = "fab fa-youtube"
	desc = "Youtube community videos"

# Developer relevant links. These will show up on right side of footer and in the community page if you have one.
[[params.links.developer]]
	name = "GitHub"
	url = "https://github.com/PadmanabhanSaravanan"
	icon = "fab fa-github"
	desc = "Development takes place here!"

[[params.links.developer]]
	name = "Slack"
	url = "https://slack.com"
	icon = "fab fa-slack"
	desc = "Chat with other project developers"

[[params.links.developer]]
	name = "Contribute"
	url = "https://git.com"
	icon = "fas fa-edit"
	desc = "Contribute to the website"

[[params.links.developer]]
	name = "Stack Overflow"
	url = "https://stackoverflow.com"
	icon = "fab fa-stack-overflow"
	desc = "Practical questions and curated answers"